import type { AppMenuItem } from "../../types/menu/types";

export const sidebarMenuConfig: AppMenuItem[] = [
  {
    type: "route",
    key: "home",
    label: "Home",
    icon: "home",
    route: "home",
  },
  {
    type: "group",
    key: "workspace",
    label: "Workspace",
    icon: "workspace",
    children: [
      {
        type: "route",
        key: "manageProjects1",
        label: "Projects",
        route: "manageProjects",
        icon: "projects",
      },
      {
        type: "route",
        key: "manageTasks1",
        label: "Tasks",
        route: "manageTasks",
        icon: "tasks",
      },
    ],
  },
  {
    type: "group",
    key: "projectsGroup",
    label: "Projects",
    icon: "projectsGroup",
    children: [
      {
        type: "group",
        key: "project1key",
        label: "Project1",
        icon: "projects",
        children: [
          {
            type: "route",
            key: "project1tasks",
            label: "Tasks",
            icon: "tasks",
            route: "manageTasks",
          },
          {
            type: "route",
            key: "project1pages",
            label: "Pages",
            icon: "projectPages",
            route: "manageTasks",
          },
        ],
      },
    ],
  },
  {
    type: "group",
    key: "settingsgroup",
    label: "Settings",
    icon: "settings",
    children: [
      {
        type: "route",
        key: "users",
        label: "Users",
        route: "manageUsers",
        icon: "users",
      },
      {
        type: "route",
        key: "roles",
        label: "Roles",
        route: "manageRoles",
        icon: "roles",
      },
      {
        type: "group",
        key: "settingsgroup",
        label: "Projects",
        icon: "projectSettings",
        children: [
          {
            type: "route",
            key: "projectTypes",
            label: "Project types",
            route: "manageProjectTypes",
            icon: "projectTypes",
          },
          {
            type: "route",
            key: "projectPriorities",
            label: "Project priorities",
            route: "manageProjectPriorities",
            icon: "priorities",
          },
          {
            type: "route",
            key: "projectStatuses",
            label: "Project statuses",
            route: "manageProjectStatuses",
            icon: "statuses",
          },
        ],
      },
      {
        type: "group",
        key: "settingsgroup",
        label: "Tasks",
        icon: "taskSettings",
        children: [
          {
            type: "route",
            key: "taskPriorities",
            label: "Priorities",
            route: "manageTaskPriorities",
            icon: "priorities",
          },
          {
            type: "route",
            key: "taskStatuses",
            label: "Task statuses",
            route: "manageTaskStatuses",
            icon: "statuses",
          },
        ],
      },
    ],
  },
  {
    type: "divider",
    key: "divider1",
  },
  {
    type: "group",
    key: "currentUserGroup",
    label: "John doe",
    icon: "currentUser",
    children: [
      {
        type: "action",
        key: "switchTopNavigation",
        label: "Top navigation",
        icon: "topNavigation",
        action: "",
      },
      {
        type: "action",
        key: "switchSideNavigation",
        label: "Side navigation",
        icon: "sideNavigation",
        action: "",
      },
      {
        type: "action",
        key: "disableNotifications",
        label: "Disable notifications",
        icon: "notificationsOff",
        action: "",
      },
      {
        type: "action",
        key: "enableNotifications",
        label: "Enable notifications",
        icon: "notifications",
        action: "",
      },
      {
        type: "action",
        key: "switchDarkTheme",
        label: "Dark theme",
        icon: "darkTheme",
        action: "",
      },
      {
        type: "action",
        key: "switchLightTheme",
        label: "Light theme",
        icon: "lightTheme",
        action: "",
      },
      {
        type: "route",
        key: "profile",
        label: "Profile",
        icon: "profile",
        route: "profile",
      },
      {
        type: "action",
        key: "logout",
        label: "Logout",
        icon: "logout",
        action: "",
      },
    ],
  },
];
